name: Core Image Buildx

on:
  push:
    # branches:
      # - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: get_tag
      run: |
        TAG=$(basename ${GITHUB_REF})
        echo "::set-output name=TAG::$TAG"

    - name: Build Core
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName: wojiushixiaobai/jms_core
        dockerUser: wojiushixiaobai
        dockerPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
        tag: ${{ steps.get_tag.outputs.TAG }},latest
        dockerFile: core/Dockerfile
        platform: linux/amd64,linux/arm64
        buildArg: Version=${{ steps.get_tag.outputs.TAG }}

    - name: Build Core for JumpServer
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName: jumpserver/jms_core
        dockerUser: wojiushixiaobai
        dockerPassword: ${{ secrets.DOCKER_HUB_TOKEN }}
        tag: ${{ steps.get_tag.outputs.TAG }},latest
        dockerFile: core/Dockerfile
        platform: linux/amd64,linux/arm64
        buildArg: Version=${{ steps.get_tag.outputs.TAG }}

    - name: Build Core for HuaweiCloud
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        dockerServer: swr.cn-south-1.myhuaweicloud.com
        imageName: swr.cn-south-1.myhuaweicloud.com/jumpserver/jms_core
        dockerUser: cn-south-1@TZZDVNMCLUKINTT3FMLI
        dockerPassword: ${{ secrets.HW_CLOUD_TOKEN }}
        tag: ${{ steps.get_tag.outputs.TAG }},latest
        dockerFile: core/Dockerfile
        platform: linux/amd64
        buildArg: Version=${{ steps.get_tag.outputs.TAG }}
